### ISSUE TITLE
Added to awesome-pocketbase

### ISSUE THREAD

**Issue by benallfree** [maxpert/marmot#13]
This is a courtesy note to say that this project is now tracked at https://github.com/benallfree/awesome-pocketbase. If you are able to add any PocketBase-specific instructions somewhere, that would be great too!

**Comment by maxpert** [comment]
> This is a courtesy note to say that this project is now tracked at https://github.com/benallfree/awesome-pocketbase. If you are able to add any PocketBase-specific instructions somewhere, that would be great too!

Good that you asked I have a [video already](https://www.youtube.com/watch?v=QqZl61bJ9BA). You can deep link that!

**Comment by benallfree** [comment]
Done :)
