### ISSUE TITLE
Inconsistent?

### ISSUE THREAD

**Issue by nkev** [maxpert/marmot#21]
Regarding "synced out of order" in your last point in the readme:

```
Marmot is eventually consistent. This simply means rows can get synced out of order, and SERIALIZABLE assumptions on transactions might not hold true anymore.
```
Does this mean nodes could become inconsistent and stay inconsistent?

**Comment by maxpert** [comment]
Not really. Eventually all the rows will be synced. As long as system is making progress it will force conversion.
