### ISSUE TITLE
Website needed

### ISSUE THREAD

**Issue by maxpert** [maxpert/marmot#3]
Just like rest of good open source projects we need a nice clean well designed static website.

**Comment by insuusvenerati** [comment]
Hi, frontend developer by profession. I'd love to help! Did you have any ideas in mind? Saw that you were also talking about getting a discord setup. I think that's a great idea, just make sure to require verified members since a lot of discord are getting bot raided lately.

**Comment by maxpert** [comment]
Yes I think I will setup a Discord/Gitter in few days. So that I can have a dedicated channel for discussion there. I TBH have no ideas in my about logo or site itself. So I am open to community suggestions

**Comment by insuusvenerati** [comment]
Any luck getting a discord set up? If you need help with it I'd be happy to. As for the website, I found a nifty way to generate one using React so I can get started in that and communicate progress in the discord.

**Comment by maxpert** [comment]
There is a discord badge now on main page, [here](https://discord.gg/GxqxpU35) is the link.
