### ISSUE TITLE
IPV6 Support

### ISSUE THREAD

**Issue by dvn0** [maxpert/marmot#4]
Doesn't seem to work with ipv6. That would be nice to have, and Go networking has pretty good support for it, in my experience. You have a lot of dependencies though, so hopefully there are no blockers.

Thanks for the useful project.

**Comment by gabrieldavid98** [comment]
Seems like ipv6 is not supported on lib used for multi-group Raft

**Comment by maxpert** [comment]
I can trace through code in dragonboat to see if passing IPv6 string will work or not.

**Comment by maxpert** [comment]
Yep just verified seems like dragonboat won't allow IPv6, might have to open ticket [here](https://github.com/lni/dragonboat) 
![image](https://user-images.githubusercontent.com/22441/190841574-8a51ff4f-2d88-416f-8dad-ae049a1dff96.png)

**Comment by maxpert** [comment]
Closing issue since it's not something fixable within scope of this project. I've opened ticket on dragonboat side though:
https://github.com/lni/dragonboat/issues/255

**Comment by ehmry** [comment]
@maxpert https://duckduckgo.com/?t=ffsb&q=how+to+copy+and+paste+text&ia=web

**Comment by dvn0** [comment]
@maxpert where is the screenshot from? i.e. which dragonboat project and file? thanks for taking a look.

**Comment by maxpert** [comment]
@dvn0 yes this is from dragonboat project itself. We will need to make a contribution to dragonboat for Marmot to use it.

**Comment by dvn0** [comment]
Thanks @maxpert, but it would be more helpful to know exactly what module contained this, so I don't have to clone everything and walk through the methods. Anyway, that's what I did and tracked it down to here: https://github.com/lni/goutils/blob/master/stringutil/regex.go#L31

**Comment by maxpert** [comment]
@dvn0 you are spot on. This is precisely the place I took snapshot from in my code.
